variables:
#  MAVEN_EXEC: C:/Maven/apache-maven-3.6.3/bin/mvn
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  HOMEPAGE_URL: http://localhost:8080/

# In addition, variables ADAP_KDB_TEST_USERNAME and ADAP_KDB_TEST_PASSWORD must be defined in GitLab CI settings.
cache:
  paths:
    - .m2/repository

build:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - mvn -version
    - mvn clean install
    - docker build -f docker/adap-kdb-docker/integration_test -t adap-kdb-img .
    - docker run -e DATABASE=host.docker.internal -d -p8080:8080 adap-kdb-img
    - python3 --version
    - python3 scripts/selenium/initial_test.py --homepage-url $HOMEPAGE_URL
  timeout: 15m
  tags:
    - test_mac

test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - pwd
    - python3 scripts/selenium/ontology_level_test.py --homepage-url $HOMEPAGE_URL --username $ADAP_KDB_TEST_USERNAME --password $ADAP_KDB_TEST_PASSWORD
    - python3 scripts/selenium/manual_search_test.py --homepage-url $HOMEPAGE_URL --identifier "eicosatrienoic acid" --spectrum "79 100; 67 90.3325; 80 75.8722; 81 59.0838; 93 54.0933"
    - python3 scripts/selenium/msp_upload_process_test.py --homepage-url $HOMEPAGE_URL --msp-path $CI_PROJECT_DIR/scripts/selenium/combined.msp
    - python3 scripts/selenium/login_register_test.py --homepage-url $HOMEPAGE_URL
    - python3 scripts/selenium/individual_search_test_without_login.py --homepage-url $HOMEPAGE_URL --msp-path $CI_PROJECT_DIR/scripts/selenium/combined.msp
    - python3 scripts/selenium/individual_search_test_after_login.py --homepage-url $HOMEPAGE_URL --msp-path $CI_PROJECT_DIR/scripts/selenium/combined.msp --user-name $ADAP_KDB_TEST_USERNAME --user-password $ADAP_KDB_TEST_PASSWORD
    - python3 scripts/selenium/group_search_test_without_login.py --homepage-url $HOMEPAGE_URL --msp-path $CI_PROJECT_DIR/scripts/selenium/combined.msp
    - python3 scripts/selenium/cluster_page_test.py --homepage-url $HOMEPAGE_URL
    - python3 scripts/selenium/upload_and_save_study_after_login.py --homepage-url $HOMEPAGE_URL --msp-path $CI_PROJECT_DIR/scripts/selenium/combined.msp  --user-name $ADAP_KDB_TEST_USERNAME --user-password $ADAP_KDB_TEST_PASSWORD
  timeout: 30m
  tags:
      - test_mac

package:
  stage: deploy
  script:
    - mvn clean install
    - docker build -f docker/adap-kdb-docker/manual_test -t adap-kdb-img .
    - docker save adap-kdb-img  > adap-kdb-img.tar
  artifacts:
    paths:
      - "adap-kdb-img.tar"
      - "scripts/script.sh"
    name: "adap-kdb-img"
    expire_in: 1 day
  only:
    - master
    - merge_requests
  timeout: 15m
  tags:
      - test_mac

