variables:
  MAVEN_EXEC: C:\Maven\apache-maven-3.6.3\bin\mvn
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  HOMEPAGE_URL: http://localhost:8080/adap_compound_db_war/

# In addition, variables ADAP_KDB_TEST_USERNAME and ADAP_KDB_TEST_PASSWORD must be defined in GitLab CI settings.

cache:
  paths:
    - .m2/repository

build:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - mvn -version
    - mvn clean install tomcat7:redeploy -Denvironment=test
    - python scripts\selenium\initial_test.py

test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - pwd
    - python --version
    - python scripts\selenium\ontology_level_test.py --homepage-url $HOMEPAGE_URL --username $ADAP_KDB_TEST_USERNAME --password $ADAP_KDB_TEST_PASSWORD
    - python scripts\selenium\manual_search_test.py --homepage-url $HOMEPAGE_URL --identifier "eicosatrienoic acid" --spectrum "79 100; 67 90.3325; 80 75.8722; 81 59.0838; 93 54.0933"
    - python scripts\selenium\msp_upload_process_test.py --homepage_url $HOMEPAGE_URL --msp_path $CI_PROJECT_DIR\scripts\selenium\combined.msp
    - python scripts\selenium\login_register_test.py --homepage_url $HOMEPAGE_URL
    - python scripts\selenium\individual_search_test_without_login.py --homepage_url $HOMEPAGE_URL --msp_path $CI_PROJECT_DIR\scripts\selenium\combined.msp
    - python scripts\selenium\individual_search_test_after_login.py --homepage_url $HOMEPAGE_URL --msp_path $CI_PROJECT_DIR\scripts\selenium\combined.msp --user_name $ADAP_KDB_TEST_USERNAME --user_password $ADAP_KDB_TEST_PASSWORD
    - python scripts\selenium\group_search_test_without_login.py --homepage_url $HOMEPAGE_URL --msp_path $CI_PROJECT_DIR\scripts\selenium\combined.msp
    - python scripts\selenium\cluster_page_test.py --homepage_url $HOMEPAGE_URL
    - mvn tomcat7:undeploy -Denvironment=test
