variables:
  MAVEN_EXEC: C:\Maven\apache-maven-3.6.3\bin\mvn
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  HOMEPAGE_URL: http://localhost:8080/adap_compound_db_war/

# In addition, variables ADAP_KDB_TEST_USERNAME and ADAP_KDB_TEST_PASSWORD must be defined in GitLab CI settings.

cache:
  paths:
    - .m2/repository

build:
  stage: build
  only:
    - master
  script:
    - mvn clean tomcat7:redeploy -Denvironment=test

test:
  stage: test
  only:
    - master
  script:
    - pwd
    - python --version
    - python scripts\selenium\initial_test.py
    - cmd /C python scripts\selenium\msp_upload_process_test.py --homepage_url %HOMEPAGE_URL% --msp_path %CI_PROJECT_DIR%\scripts\selenium\combined.msp
    - cmd /C python scripts\selenium\login_register_test.py --homepage_url %HOMEPAGE_URL%
    - cmd /C python scripts\selenium\individual_search_test_without_login.py --homepage_url %HOMEPAGE_URL% --msp_path %CI_PROJECT_DIR%\scripts\selenium\combined.msp
    - cmd /C python scripts\selenium\individual_search_test_after_login.py --homepage_url %HOMEPAGE_URL% --msp_path %CI_PROJECT_DIR%\scripts\selenium\combined.msp --user_name %ADAP_KDB_TEST_USERNAME% --user_password %ADAP_KDB_TEST_PASSWORD%
    - cmd /C python scripts\selenium\group_search_test_without_login.py --homepage_url %HOMEPAGE_URL% --msp_path %CI_PROJECT_DIR%\scripts\selenium\combined.msp
    - cmd /C python scripts\selenium\cluster_page_test.py --homepage_url %HOMEPAGE_URL%
    - mvn tomcat7:undeploy -Denvironment=test
