variables:
  MAVEN_EXEC: C:\Maven\apache-maven-3.6.3\bin\mvn
  HOMEPAGE_URL: http://localhost:8080/adap_compound_db_war/

build:
  stage: build
  only:
    - master
  script:
    - cmd /C %MAVEN_EXEC% tomcat7:redeploy -Denvironment=test

test:
  stage: test
  only:
    - master
  script:
    - python scripts\selenium\initial_test.py
    - cmd /C python scripts\selenium\msp_upload_process_test.py --homepage_url %HOMEPAGE_URL% --msp_path %CI_PROJECT_DIR%\scripts\selenium\combined.msp
    - cmd /C python scripts\selenium\login_register_test.py --homepage_url %HOMEPAGE_URL%
