variables:
  MAVEN_EXEC: C:\Maven\apache-maven-3.6.3\bin\mvn

build:
  stage: build
  script:
    - cmd /C %MAVEN_EXEC% tomcat7:redeploy -Denvironment=test
    - cmd /C echo %CI_JOB_ID%

test:
  stage: test
  script:
    - echo %CI_BUILDS_DIR%
    - python %CI_BUILDS_DIR%/scripts/selenium/initial_test.py
