variables:
  MAVEN_EXEC: C:\Maven\apache-maven-3.6.3\bin\mvn

build:
  stage: build
  only:
    - master
  script:
    - cmd /C %MAVEN_EXEC% tomcat7:redeploy -Denvironment=test

test:
  stage: test
  only:
    - master
  script:
    - python scripts\selenium\initial_test.py
