/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-05-29 15:39:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/Applications/tomcat/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1589904292000L));
    _jspx_dependants.put("jar:file:/Applications/tomcat/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/tld/dulab.tld", Long.valueOf(1589904292000L));
    _jspx_dependants.put("jar:file:/Applications/tomcat/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153399482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<section>\n");
      out.write("    <div class=\"tabbed-pane\">\n");
      out.write("        <span class=\"active\" data-tab=\"tools\">Tools</span>\n");
      out.write("        <span data-tab=\"users\">All Users</span>\n");
      out.write("        <span data-tab=\"submissions\">All Studies</span>\n");
      out.write("        <span data-tab=\"feedback\">Feedback</span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"tools\">\n");
      out.write("        <div>\n");
      out.write("            <div id=\"progressBarDiv\" class=\"progress_bar\"></div>\n");
      out.write("        </div>\n");
      out.write("        <h2>Number of Spectra in Knowledgebase</h2>\n");
      out.write("        <div align=\"center\">\n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <th></th>\n");
      out.write("                    <th>Submitted</th>\n");
      out.write("                    <th>Unmatched</th>\n");
      out.write("                    <th>Consensus</th>\n");
      out.write("                    <th>Matches</th>\n");
      out.write("                </tr>\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("</table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <h3>Admin Tools</h3>\n");
      out.write("        <div>\n");
      out.write("            <table style=\"width: 100%;\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr><th class=\"desktop\" style=\"width: 20%;\"></th><th style=\"width: 25%;\"></th><th></th></tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"desktop\">Calculates matching scores for all spectra in the Knowledgebase</td>\n");
      out.write("                        <td>\n");
      out.write("                            <!-- <a href=\"calculatescores/\" class=\"button\"\n");
      out.write("                                onclick=\"progressBar.start('calculatescores/progress')\">Calculate Matching Scores...</a> -->\n");
      out.write("                            <button class=\"button\" id=\"calculate_match_button\" style=\"width: 100%;\">Calculate Matching Scores</button>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <progress id=\"match_progress\" value=\"0\" max=\"100\" style=\"width:100%; height: 1.4em;\"></progress>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"desktop\">Cluster spectra into clusters</td>\n");
      out.write("                        <td>\n");
      out.write("                            <!-- <a id=\"button-cluster\" href=\"cluster/\"\n");
      out.write("                                class=\"button\">Cluster spectra...</a> -->\n");
      out.write("                            <button class=\"button\" id=\"cluster_button\" style=\"width: 100%;\">Cluster spectra</button>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <progress id=\"cluster_progress\" value=\"0\" max=\"100\" style=\"width:100%; height: 1.4em;\"></progress>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"users\" class=\"\">\n");
      out.write("        <div align=\"center\">\n");
      out.write("            <table id=\"user_table\" class=\"display\" style=\"width: 100%;\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>User</th>\n");
      out.write("                        <th>Email</th>\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("<th></th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("</tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"submissions\" class=\"\">\n");
      out.write("        <table id=\"submission_table\" class=\"display\" style=\"width: 100%;\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>ID</th>\n");
      out.write("                    <th>Date / Time</th>\n");
      out.write("                    <th>Name</th>\n");
      out.write("                    <th>External ID</th>\n");
      out.write("                    <th>User</th>\n");
      out.write("                    <th>Properties</th>\n");
      out.write("                    <th>Reference (Off/On)</th>\n");
      out.write("                    <th></th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"feedback\" class=\"\">\n");
      out.write("        <table id=\"feedback_table\" class=\"display\" style=\"width: 100%;\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Id</th>\n");
      out.write("                    <th>Message</th>\n");
      out.write("                    <th></th>\n");
      out.write("                    <th>By</th>\n");
      out.write("                    <th>Date</th>\n");
      out.write("                    <th></th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<div id=\"confirm-delete-dialog\"></div>\n");
      out.write("<div id=\"progress-dialog\"></div>\n");
      out.write("\n");
      out.write("<!-- End the middle column -->\n");
      out.write("\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("<script>\n");
      out.write("var confirmDeleteDialog = $('#confirm-delete-dialog').confirmDeleteDialog();\n");
      out.write("    var progressDialog = $('#progress-dialog').progressDialog();\n");
      out.write("    var markRead = function(obj) {\n");
      out.write("        $(obj).closest(\"tr\").find(\"td:eq(2)\").find(\"i\").html(\"drafts\");\n");
      out.write("    };\n");
      out.write("\n");
      out.write("    $(document).ready(function () {\n");
      out.write("        $('#cluster_table').DataTable();\n");
      out.write("        $('#user_table').DataTable({\n");
      out.write("            scrollX: true,\n");
      out.write("            scroller: true,\n");
      out.write("            \"fnInitComplete\": function (oSettings, json) {\n");
      out.write("                $(\"#users\").addClass(\"hide\");\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('#submission_table').DataTable({\n");
      out.write("            \"order\": [[1, \"desc\"]],\n");
      out.write("            serverSide: true,\n");
      out.write("            processing: true,\n");
      out.write("            scrollX: true,\n");
      out.write("            scroller: true,\n");
      out.write("            ajax: {\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/submission/findAllSubmissions.json\",\n");
      out.write("    \n");
      out.write("                data: function (data) {\n");
      out.write("                    data.column = data.order[0].column;\n");
      out.write("                    data.sortDirection = data.order[0].dir;\n");
      out.write("                    data.search = data.search[\"value\"];\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            \"columnDefs\": [\n");
      out.write("                {\n");
      out.write("                    \"targets\": 0,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"data\": \"id\"\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 1,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"data\": \"formattedDate\"\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 2,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        content = '<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/submission/' + row.id + '/\">' +\n");
      out.write("                            row.name +\n");
      out.write("                            '</a>';\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 3,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        if (row.externalId == null){\n");
      out.write("                            content = ''\n");
      out.write("                        } else {\n");
      out.write("                            content = row.externalId;\n");
      out.write("                        }\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 4,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        content = row.user.name + '<br/><small>' + row.user.email + '<small>';\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 5,\n");
      out.write("                    \"orderable\": false,\n");
      out.write("                    \"data\": \"tagsAsString\"\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 6,\n");
      out.write("                    \"orderable\": false,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        var content = '<label class=\"switch\" id=\"reference_checkbox\">' +\n");
      out.write("                            '<input type=\"checkbox\" value=\"' + row.id + '\" ';\n");
      out.write("                        if(row.allSpectrumReference == 1) {\n");
      out.write("                            content += 'checked'\n");
      out.write("                        }\n");
      out.write("                        content += '><span class=\"checkbox-slider ';\n");
      out.write("                        if(row.allSpectrumReference == null) {\n");
      out.write("                            content += 'translate-middle';\n");
      out.write("                        }\n");
      out.write("                        content += '\"></span></label>';\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 7,\n");
      out.write("                    \"orderable\": false,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        var clickEve = \"confirmDeleteDialog.show(\" +\n");
      out.write("                            \"'Submission &quot;\" + row.name + \"&quot; and all its spectra will be deleted. Are you sure?',\" +\n");
      out.write("                            \"'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/submission/\" + row.id + \"/delete/');\";\n");
      out.write("                        var content = '<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/submission/' + row.id + '/\">' +\n");
      out.write("                            '<i class=\"material-icons\" title=\"View\">&#xE5D3;</i>' +\n");
      out.write("                            '</a>' +\n");
      out.write("                            '<a onclick=\"' + clickEve + '\">' +\n");
      out.write("                            '<i class=\"material-icons\" title=\"Delete\">&#xE872;</i></a>';\n");
      out.write("    \n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            ],\n");
      out.write("            \"fnInitComplete\": function (oSettings, json) {\n");
      out.write("                $(\"#submissions\").addClass(\"hide\");\n");
      out.write("            }\n");
      out.write("        }).on('draw', function() {\n");
      out.write("            $(\"#reference_checkbox > input[type='checkbox']\").each(function() {\n");
      out.write("                $(this).on(\"change\", function() {\n");
      out.write("                    $(this).parent().find(\"span.checkbox-slider\").removeClass(\"translate-middle\");\n");
      out.write("                    updateReferenceOfAllSpectraOfSubmission($(this).val(), $(this).is(\":checked\"));\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("\n");
      out.write("        $('#feedback_table').DataTable({\n");
      out.write("            \"order\": [[3, \"desc\"]],\n");
      out.write("            serverSide: true,\n");
      out.write("            processing: true,\n");
      out.write("            scrollX: true,\n");
      out.write("            scroller: true,\n");
      out.write("            ajax: {\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/feedback/findAllFeedback.json\",\n");
      out.write("    \n");
      out.write("                data: function (data) {\n");
      out.write("                    data.column = data.order[0].column;\n");
      out.write("                    data.sortDirection = data.order[0].dir;\n");
      out.write("                    data.search = data.search[\"value\"];\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            \"columnDefs\": [\n");
      out.write("                {\n");
      out.write("                    \"targets\": 0,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"data\": \"id\"\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 1,\n");
      out.write("                    \"orderable\": false,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        msg = row.message;\n");
      out.write("                        if(msg.length > 20) {\n");
      out.write("                            msg = msg.substr(0, 20) + \"...\";\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                        content = '<span title=\"' + row.message.substr(0, 500) + '\">'\n");
      out.write("                                        + msg + '</span>';\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 2,\n");
      out.write("                    \"orderable\": false,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        if(row.read) {\n");
      out.write("                            content = '<i class=\"material-icons\">drafts</i>';\n");
      out.write("                        } else {\n");
      out.write("                            content = '<i class=\"material-icons\">mail</i>';\n");
      out.write("                        }\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 3,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        content = row.name\n");
      out.write("                                        + '<br/>'\n");
      out.write("                                        + '<small>' + row.email + '<small>'\n");
      out.write("                                        + '<br/>'\n");
      out.write("                                        + '<small>Affiliation: ' + row.affiliation + '<small>';\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 4,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        content = row.submitDate;\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                {\n");
      out.write("                    \"targets\": 5,\n");
      out.write("                    \"orderable\": true,\n");
      out.write("                    \"render\": function (data, type, row, meta) {\n");
      out.write("                        content = '<a onclick=\"markRead(this);\" target=\"_blank\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/feedback/' + row.id + '/\">' +\n");
      out.write("                            '<i class=\"material-icons\" title=\"View\">&#xE5D3;</i>' +\n");
      out.write("                            '</a>';\n");
      out.write("                        return content;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            ],\n");
      out.write("            \"fnInitComplete\": function (oSettings, json) {\n");
      out.write("                $(\"#feedback\").addClass(\"hide\");\n");
      out.write("            }\n");
      out.write("        })\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    function updateReferenceOfAllSpectraOfSubmission(submissionId, reference) {\n");
      out.write("        $.ajax({\n");
      out.write("              url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/spectrum/updateReferenceOfAllSpectraOfSubmission\",\n");
      out.write("              type: \"GET\",\n");
      out.write("              contentType: 'application/json; charset=utf-8',\n");
      out.write("              data: {\"value\": reference, \"submissionId\": submissionId},\n");
      out.write("              success: function (r) {\n");
      out.write("              },\n");
      out.write("              error: function (xhr) {\n");
      out.write("                  alert('Error while selecting list..!!');\n");
      out.write("              }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    var clusterButton = $('#cluster_button');\n");
      out.write("    var matchButton = $('#calculate_match_button');\n");
      out.write("    $(clusterButton).attr(\"disabled\", \"disabled\");\n");
      out.write("    $(matchButton).attr(\"disabled\", \"disabled\");\n");
      out.write("\n");
      out.write("    var counter = 0;\n");
      out.write("    var buttonHandler = function() {\n");
      out.write("        counter++;\n");
      out.write("        if(counter >= 2) {\n");
      out.write("            $(clusterButton).removeAttr(\"disabled\");\n");
      out.write("            $(matchButton).removeAttr(\"disabled\");\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    var scoreProgressBar = new ProgressBar('calculatescores/progress', 'match_progress', 3000, buttonHandler);\n");
      out.write("    var clusterProgressBar = new ProgressBar('cluster/progress', 'cluster_progress', 500, buttonHandler);\n");
      out.write("\n");
      out.write("    scoreProgressBar.start();\n");
      out.write("    clusterProgressBar.start();\n");
      out.write("\n");
      out.write("    $(matchButton).click(function () {\n");
      out.write("        $(clusterButton).attr(\"disabled\", \"disabled\");\n");
      out.write("        $(matchButton).attr(\"disabled\", \"disabled\");\n");
      out.write("        $.ajax({\n");
      out.write("            url: \"admin/calculatescores\"\n");
      out.write("        }).done(function() {\n");
      out.write("            $(\"#match_progress\").removeClass(\"hide\");\n");
      out.write("            scoreProgressBar.start();\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(clusterButton).click(function () {\n");
      out.write("        $(clusterButton).attr(\"disabled\", \"disabled\");\n");
      out.write("        $(matchButton).attr(\"disabled\", \"disabled\");\n");
      out.write("        $.ajax({\n");
      out.write("            url: \"admin/cluster\"\n");
      out.write("        }).done(function() {\n");
      out.write("            $(\"#cluster_progress\").removeClass(\"hide\");\n");
      out.write("            clusterProgressBar.start(); \n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("    $(\".tabbed-pane\").each(function() {\n");
      out.write("        $(this).tabbedPane();\n");
      out.write("    });\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(33,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/view/admin/admin.jsp(33,16) '${statistics}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${statistics}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/view/admin/admin.jsp(33,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("mapEntry");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<tr>\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapEntry.key.label}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapEntry.value.numSubmittedSpectra}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapEntry.value.numUnmatchedSpectra}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapEntry.value.numConsensusSpectra}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapEntry.value.numSpectrumMatches}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                    </tr>\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(86,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/view/admin/admin.jsp(86,24) '${availableUserRoles}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${availableUserRoles}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/view/admin/admin.jsp(86,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("role");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<th>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${role.label}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(94,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/view/admin/admin.jsp(94,20) '${users}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${users}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/view/admin/admin.jsp(94,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("user");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<tr>\n");
            out.write("                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                            ");
            if (_jspx_meth_c_005fforEach_005f3(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("<td><a onclick=\"confirmDeleteDialog.show(\n");
            out.write("                                'User &quot;");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&quot; and all user\\'s studies will be deleted. Are you sure?',\n");
            out.write("                                '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/user/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/delete');\">\n");
            out.write("                                    <i class=\"material-icons\">delete</i>\n");
            out.write("                            </a></td>\n");
            out.write("                        </tr>\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/jsp/view/admin/admin.jsp(98,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/view/admin/admin.jsp(98,28) '${availableUserRoles}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${availableUserRoles}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/view/admin/admin.jsp(98,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("role");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<td>");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
              return true;
            out.write("</td>\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f3);
      // /WEB-INF/jsp/view/admin/admin.jsp(100,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.roles.contains(role)}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<i class=\"material-icons\">check</i>\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(159,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/jQuery-3.2.1/jquery-3.2.1.min.js");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(160,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/DataTables-1.10.16/js/jquery.dataTables.min.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(161,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/jquery-ui-1.12.1/jquery-ui.min.js");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(162,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/AdapCompoundDb/js/dialogs.js");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(163,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/resources/AdapCompoundDb/js/progressBar.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/jsp/view/admin/admin.jsp(164,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/resources/AdapCompoundDb/js/tabs.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }
}
